package edu.uob;

public enum NodeType {
    // AST node types
    COMMAND, COMMAND_TYPE, USE, CREATE, CREATE_DATABASE, CREATE_TABLE, DROP,
    ALTER, INSERT, SELECT, UPDATE, DELETE, JOIN, DIGIT, UPPER_CASE, LOWER_CASE,
    LETTER, PLAIN_TEXT, SYMBOL, SPACE, NAME_VALUE_LIST, NAME_VALUE_PAIR,
    ALTERATION_TYPE, VALUE_LIST, DIGIT_SEQUENCE, INTEGER_LITERAL, FLOAT_LITERAL,
    BOOLEAN_LITERAL, CHAR_LITERAL, STRING_LITERAL, VALUE, TABLE_NAME, ATTRIBUTE_NAME,
    DATABASE_NAME, WILD_ATTRIBUTE_LIST, ATTRIBUTE_LIST, CONDITION,
    BOOLEAN_OPERATOR, COMPARATOR
}
