package edu.uob;

public enum Token {
    // AST node types
    COMMAND, COMMAND_TYPE, USE, CREATE, CREATE_DATABASE, CREATE_TABLE, DROP,
    ALTER, INSERT, SELECT, UPDATE, DELETE, JOIN, DIGIT, UPPER_CASE, LOWER_CASE,
    LETTER, PLAIN_TEXT, SYMBOL, SPACE, NAME_VALUE_LIST, NAME_VALUE_PAIR,
    ALTERATION_TYPE, VALUE_LIST, DIGIT_SEQUENCE, INTEGER_LITERAL, FLOAT_LITERAL,
    BOOLEAN_LITERAL, CHAR_LITERAL, STRING_LITERAL, VALUE, TABLE_NAME, ATTRIBUTE_NAME,
    DATABASE_NAME, WILD_ATTRIBUTE_LIST, ATTRIBUTE_LIST, CONDITION,
    BOOLEAN_OPERATOR, COMPARATOR,

    // Keyword (KW) types -- these are not AST node types, by we need them for the initial lexical parse
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, EQUALS_KW, COMMA_KW, MINUS_KW, PLUS_KW, DOT_KW,
    APOSTROPHE_KW, EQ_KW, LESS_KW, MORE_KW, LTEQ_KW, GTEQ_KW, NOT_EQ_KW,
    USE_KW, CREATE_DB_KW, CREATE_TABLE_KW, DROP_DB_KW, DROP_TABLE_KW, ALTER_TABLE_KW,
    INSERT_INTO_KW, VALUES_KW, SELECT_KW, FROM_KW, WHERE_KE, UPDATE_KW, SET_KW,
    DELETE_FROM_KW, JOIN_KW, AND_KW, ON_KW, ADD_KW, DROP_KW, TRUE_KW, FALSE_KW,
    NULL_KW, ASTRISK_KW, OR_KW, LIKE_KW
}
